// examples/sveltekit-houdini/src/routes/+page.svelte
<script lang="ts">
	import type { PageData, ActionData } from './$houdini';
	import { enhance } from '$app/forms';

	export let data: PageData;

	export let form: ActionData;

	$: ({ GetAllMessages } = data);
</script>

<h1>Grafbook</h1>

<form method="POST" action="?/auth" use:enhance>
	<button name="role" value="">Set role to public</button>
	<button name="role" value="moderator">
		Set role to moderator
	</button>
	<button name="role" value="admin">Set role to admin</button>
</form>

<form method="POST" action="?/add" use:enhance>
	<fieldset>
		<legend>New message</legend>
		<div>
			<input type="text" name="author" placeholder="Name" required />
		</div>
		<div>
			<textarea name="message" placeholder="Write a message..." required rows={5} />
		</div>
		<div>
			<button type="submit">Add message</button>
		</div>
</fieldset>
</form>

{#if $GetAllMessages.fetching}
	loading...
{:else if $GetAllMessages.errors?.length}
	{JSON.stringify($GetAllMessages)}
{:else}
	<ul>
		{#each $GetAllMessages.data?.messageCollection?.edges as { node }}
		<li>
			<p>
				<strong>
					<span>
						{node?.author}
					</span>
				<br />
				<small>{new Intl.DateTimeFormat('en-GB', {
                    dateStyle: 'medium',
                    timeStyle: 'short'
                  }).format(Date.parse(node?.createdAt))}</small>
									</strong>
			</p>
            <p>{node.message}</p>
		</li>
	{/each}
	</ul>
{/if}

// examples/fresh/routes/index.tsx
import { Handlers, PageProps } from '$fresh/server.ts'
import { grafbaseClient } from '@/utils/grafbase'

type Message = {
  id: string
  author: string
  message: string
  createdAt: string
}

const GetAllMessagesQuery = /* GraphQL */ `
  query GetAllMessages($first: Int!) {
    messageCollection(first: $first) {
      edges {
        node {
          id
          author
          message
          createdAt
        }
      }
    }
  }
`

const AddNewMessageMutation = /* GraphQL */ `
  mutation AddNewMessage($author: String!, $message: String!) {
    messageCreate(input: { author: $author, message: $message }) {
      message {
        id
      }
    }
  }
`

export const handler: Handlers = {
  async GET(_, ctx) {
    const response = await grafbaseClient({
      query: GetAllMessagesQuery,
      variables: {
        first: 100
      }
    })

    if (!response.ok) {
      return ctx.render(null)
    }

    const { data } = await response.json()

    return ctx.render(data)
  },
  async POST(req, ctx) {
    const formData = await req.formData()
    const json = Object.fromEntries(formData)

    await grafbaseClient({
      query: AddNewMessageMutation,
      variables: {
        author: json.author,
        message: json.message
      }
    })

    const response = await grafbaseClient({
      query: GetAllMessagesQuery,
      variables: {
        first: 100
      }
    })

    const { data } = await response.json()

    return ctx.render(data)
  }
}

export default function IndexPage({
  data
}: PageProps<{ messageCollection: { edges: { node: Message }[] } }>) {
  return (
    <>
      <h1>Grafbook</h1>
      <form method="POST">
        <fieldset>
          <legend>New message</legend>
          <input id="author" name="author" placeholder="Name" />
          <br />
          <textarea
            id="message"
            name="message"
            placeholder="Write a message..."
            rows={5}
          ></textarea>
          <br />
          <button type="submit">Submit</button>
        </fieldset>
      </form>
      <ul>
        {data?.messageCollection?.edges?.map(({ node }) => (
          <li key={node.id}>
            <p>
              <strong>
                <a href={`/messages/${node.id}`}>{node.author}</a>
                <br />
                <small>
                  {new Intl.DateTimeFormat('en-GB', {
                    dateStyle: 'medium',
                    timeStyle: 'short'
                  }).format(Date.parse(node.createdAt))}
                </small>
              </strong>
            </p>
            <p>{node.message}</p>
          </li>
        ))}
      </ul>
    </>
  )
}
