// examples/solid/src/components/todo-list.tsx
import debounce from 'lodash.debounce'
import { For, Match, Switch } from 'solid-js'
import { createMutation } from 'solid-urql'

import { Dropdown, DropdownItem } from '~/components/dropdown'
import {
  DotsVerticalIcon,
  PencilIcon,
  SpinnerIcon,
  TrashIcon
} from '~/components/icons'
import TodoItem from '~/components/todo-item'
import TodoItemCreate from '~/components/todo-item-create'
import {
  TodoListDeleteDocument,
  TodoListFragment,
  TodoListUpdateDocument
} from '~/graphql/schema'
import getColor from '~/utils/get-color'

const TodoListDeleteContext = { additionalTypenames: ['TodoList', 'Todo'] }

const TodoList = (props: TodoListFragment) => {
  const { id, title, todos } = props
  let inputRef: HTMLInputElement

  const [deleting, todoListDelete] = createMutation(TodoListDeleteDocument)
  const [_, todoListUpdate] = createMutation(TodoListUpdateDocument)

  const onTitleChange = debounce((title: string) => {
    todoListUpdate({ id, title })
  }, 500)

  return (
    <div class="space-y-4 flex-1 min-w-[300px]">
      <div
        class="flex justify-between border-b-2"
        title={title || ''}
        style={{ borderColor: getColor(id) }}
      >
        <h2 class="text-xl font-bold truncate">
          <input
            ref={(el) => (inputRef = el)}
            required
            type="text"
            name="title"
            value={title}
            onChange={(e) => onTitleChange(e.currentTarget.value)}
            class="bg-transparent focus:outline-0 focus:text-blue-600 focus:dark:text-blue-400"
          />
        </h2>
        <div class="relative z-20">
          <Switch>
            <Match when={deleting().fetching}>
              <SpinnerIcon />
            </Match>
            <Match when={!deleting().fetching}>
              <Dropdown
                trigger={
                  <DotsVerticalIcon class="w-5 h-5 text-gray-400 transition hover:text-red-400" />
                }
              >
                <DropdownItem>
                  <button
                    onClick={() => setTimeout(() => inputRef.focus(), 100)}
                    class="flex items-center w-full px-2 py-2 text-sm rounded-md group hover:bg-emerald-200 hover:dark:bg-emerald-700"
                  >
                    <PencilIcon class="w-5 h-5 mr-3" aria-hidden="true" />
                    Rename
                  </button>
                </DropdownItem>
                <DropdownItem>
                  <button
                    disabled={deleting().fetching}
                    onClick={() =>
                      todoListDelete({ id }, TodoListDeleteContext)
                    }
                    class="flex items-center w-full px-2 py-2 text-sm rounded-md group hover:bg-emerald-200 hover:dark:bg-emerald-700"
                  >
                    <TrashIcon class="w-5 h-5 mr-3" aria-hidden="true" />
                    Delete
                  </button>
                </DropdownItem>
              </Dropdown>
            </Match>
          </Switch>
        </div>
      </div>
      <div class="space-y-4">
        <For each={todos}>{(todo) => !!todo && <TodoItem {...todo} />}</For>
      </div>
      <TodoItemCreate todoListId={id} />
    </div>
  )
}

export default TodoList

// examples/remix/app/components/todo-list.tsx
import { useFetcher } from '@remix-run/react'
import debounce from 'lodash.debounce'
import { useRef } from 'react'
import { Dropdown, DropdownItem } from '~/components/dropdown'
import { DotsVerticalIcon, PencilIcon, TrashIcon } from '~/components/icons'
import TodoItem from '~/components/todo-item'
import TodoItemCreate from '~/components/todo-item-create'
import type { TodoListFragment } from '~/graphql/schema'
import getColor from '~/utils/get-color'

const dropdownItemClass =
  'flex items-center w-full px-2 py-2 text-sm rounded-md group hover:bg-emerald-200 hover:dark:bg-emerald-700'

const TodoList = (props: TodoListFragment) => {
  const { id, title, todos } = props
  const { Form, submission, submit } = useFetcher()
  const inputRef = useRef<HTMLInputElement>(null)

  const isDeleting = submission?.formData.get('_action') === 'todo-list-delete'

  const onTodoListUpdate = (data: { title: string }) => {
    const form = new FormData()
    form.set('_action', 'todo-list-update')
    Object.entries({ id, ...data }).forEach(([key, value]) =>
      form.set(key, `${value}`)
    )
    return submit(form, { method: 'post' })
  }
  const onTitleChange = debounce(
    (title: string) => onTodoListUpdate({ title }),
    500
  )

  return (
    <div hidden={isDeleting} className="space-y-4 flex-1 min-w-[300px]">
      <div
        className="flex justify-between border-b-2"
        title={title || ''}
        style={{ borderColor: getColor(id) }}
      >
        <h2 className="text-xl font-bold truncate">
          <input
            ref={inputRef}
            required
            type="text"
            name="title"
            defaultValue={title}
            onChange={(e) => onTitleChange(e.target.value)}
            className="bg-transparent focus:outline-0 focus:text-blue-600 focus:dark:text-blue-400"
          />
        </h2>
        <div className="relative z-20">
          <Dropdown
            trigger={
              <DotsVerticalIcon className="w-5 h-5 text-gray-400 transition hover:text-red-400" />
            }
          >
            <DropdownItem>
              <button
                onClick={() => setTimeout(() => inputRef.current?.focus(), 100)}
                className={dropdownItemClass}
              >
                <PencilIcon className="w-5 h-5 mr-3" aria-hidden="true" />
                Rename
              </button>
            </DropdownItem>
            <DropdownItem>
              <Form method="post">
                <input type="hidden" name="id" value={id} hidden />
                <button
                  type="submit"
                  name="_action"
                  value="todo-list-delete"
                  aria-label="Delete todo"
                  disabled={isDeleting}
                  className={dropdownItemClass}
                >
                  <TrashIcon className="w-5 h-5 mr-3" aria-hidden="true" />
                  Delete
                </button>
              </Form>
            </DropdownItem>
          </Dropdown>
        </div>
      </div>
      <div className="space-y-4">
        {todos?.map((todo) => !!todo && <TodoItem key={todo.id} {...todo} />)}
      </div>
      <TodoItemCreate todoListId={id} />
    </div>
  )
}

export default TodoList
