// examples/nextjs/src/pages/index.tsx
import type { NextPage } from 'next'
import { useQuery } from 'urql'
import { TodoListsDocument } from 'graphql/schema'
import TodoList from 'components/todo-list'
import TodoListEmpty from 'components/new-todo-list'
import { useMemo } from 'react'

const Home: NextPage = () => {
  const context = useMemo(
    () => ({ additionalTypenames: ['TodoList', 'Todo'] }),
    []
  )

  const [{ data, fetching }] = useQuery({ query: TodoListsDocument, context })

  const reversed = useMemo(() => {
    if (!data?.todoListCollection?.edges) {
      return
    }

    return [...data?.todoListCollection?.edges].reverse()
  }, [data])

  if (fetching) {
    return <div>Loading...</div>
  }

  return (
    <div className="flex gap-6">
      {reversed?.map((todoList, index) => {
        if (!todoList?.node) {
          return null
        }

        return <TodoList key={index} {...todoList.node} />
      })}
      <TodoListEmpty />
    </div>
  )
}

export default Home

// examples/nuxt/src/pages/index.vue
<script setup lang="ts">
import { useQuery } from "@urql/vue";
import { TodoListsDocument } from "@/graphql/schema";

const { data, fetching, error } = useQuery({ query: TodoListsDocument });
</script>

<template>
  <div>
    <div v-if="fetching">Loading...</div>
    <div v-else-if="error">{{ error }}</div>
    <div v-else-if="data" class="flex gap-6">
      <div
        v-for="list in data.todoListCollection?.edges?.slice().reverse()"
        :key="list?.node?.id"
      >
        <TodoList v-if="list?.node?.id" v-bind="list.node" />
      </div>
      <TodoListCreate />
    </div>
  </div>
</template>
