// examples/react-apollo-live/src/App.tsx
import { useUser } from '@clerk/clerk-react'
import { useEffect, useState } from 'react'
import { gql, useQuery, useMutation } from '@apollo/client'

type Message = {
  id: string
  author: string
  message: string
  createdAt: string
}

const GetAllMessagesQuery = gql`
  query GetAllMessages($first: Int!) @live {
    messageCollection(first: $first) {
      edges {
        node {
          id
          author
          message
          createdAt
        }
      }
    }
  }
`

const AddNewMessageMutation = gql`
  mutation AddNewMessage($author: String!, $message: String!) {
    messageCreate(input: { author: $author, message: $message }) {
      message {
        id
      }
    }
  }
`

function App() {
  const { data, loading, error } = useQuery<{
    messageCollection: { edges: { node: Message }[] }
  }>(GetAllMessagesQuery, { variables: { first: 100 } })
  const [addNewMessage] = useMutation(AddNewMessageMutation)

  const { user } = useUser()
  const [author, setAuthor] = useState('')
  const [message, setMessage] = useState('')
  useEffect(() => {
    if (user?.username) {
      setAuthor(user.username)
    }
  }, [])

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error : {error.message}</p>

  return (
    <>
      <h1>Grafbook</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault()
          if (author && message) {
            addNewMessage({ variables: { author, message } })
            setMessage('')
          }
        }}
      >
        <fieldset>
          <legend>New message</legend>
          <input
            id="author"
            name="author"
            placeholder="Name"
            value={author}
            onChange={(e) => setAuthor(e.target.value)}
          />
          <br />
          <textarea
            id="message"
            name="message"
            placeholder="Write a message..."
            rows={5}
            value={message}
            onChange={(e) => setMessage(e.target.value)}
          ></textarea>
          <br />
          <button type="submit">Submit</button>
        </fieldset>
      </form>
      <ul>
        {data?.messageCollection?.edges?.map(({ node }) => (
          <li key={node.id}>
            <p>
              <strong>
                <span>{node.author}</span>
                <br />
                <small>
                  {new Intl.DateTimeFormat('en-GB', {
                    dateStyle: 'medium',
                    timeStyle: 'short'
                  }).format(Date.parse(node.createdAt))}
                </small>
              </strong>
            </p>
            <p>{node.message}</p>
          </li>
        ))}
      </ul>
    </>
  )
}

export default App

// examples/qwik/src/app.tsx
import { component$, useSignal, useTask$ } from '@builder.io/qwik';


type Message = {
  id: string
  author: string
  message: string
  createdAt: string
}

export const GetAllMessagesQuery = /* GraphQL */ `
  query GetAllMessages($first: Int!) {
    messageCollection(first: $first) {
      edges {
        node {
          id
          author
          message
          createdAt
        }
      }
    }
  }
  `

export default component$(() => {
  const messages = useSignal<Message[]>([])

  useTask$(async () => {

    const response = await fetch(`http://127.0.0.1:4000/graphql`,
    { 
      method: 'POST',
      headers: {
      'content-type': 'application/json',
     // to do: 'authorization': `BEARER {token}`
      },
      body: JSON.stringify({ 
        query: GetAllMessagesQuery,
        variables: {
          first: 100
        } 
      }) 
    });
    messages.value = await response.json();
  });

  return (
    <div>
       <ul>
        {messages.value.data?.messageCollection?.edges?.map(({ node }) => (
          <li key={node.id}>
            <p>
              <strong>
                <span>{node.author}</span>
                <br />
                <small>
                  {new Intl.DateTimeFormat('en-GB', {
                    dateStyle: 'medium',
                    timeStyle: 'short'
                  }).format(Date.parse(node.createdAt))}
                </small>
              </strong>
            </p>
            <p>{node.message}</p>
          </li>
        ))}
      </ul>
    </div>
  );
});
