// examples/nextjs/src/pages/sign-in.tsx
import type { NextPage } from "next";
import { getSession, signIn } from "next-auth/react";
import type { NextPageContext } from "next";

const Home: NextPage = () => {
  return (
    <div className="flex-1 py-36 flex item-center justify-center animate-show">
      <div className="h-fit shadow-lg rounded-lg border border-gray-200 p-6 space-y-2">
        <h2 className="text-lg font-medium">Todo Example</h2>
        <button
          className="bg-black text-white rounded-md px-2 py-1 hover:bg-gray-800 transition"
          onClick={() => signIn("github")}
        >
          Sign In With Github
        </button>
      </div>
    </div>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);

  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}

export default Home;

// examples/nuxtjs/src/pages/sign-in.vue
<template>
  <div class="flex justify-center flex-1 py-36 item-center animate-show">
    <div
      class="flex flex-col items-center p-6 space-y-4 border border-gray-200 rounded-lg shadow-lg h-fit dark:border-gray-700"
    >
      <h2 class="text-xl font-semibold">Nuxt.js - Todo Example</h2>
      <button
        @click="githubLogin"
        class="flex items-center px-5 py-3 space-x-2 text-white bg-black rounded-lg dark:bg-zinc-700 hover:bg-gray-900"
      >
        <IconRadixIconsGithubLogo />
        <span>Sign In with GitHub</span>
      </button>
    </div>
  </div>
</template>
