// examples/sveltekit/src/routes/__layout.svelte
<script lang="ts">
	import Header from '$lib/Header.svelte';
	import '../app.css';
</script>

<Header />

<main class="relative h-[calc(100vh_-_64px)] flex pl-6 pt-6 pr-12 overflow-x-auto dark:bg-zinc-900">
	<div
		class="fixed left-0 w-6 h-full bg-gradient-to-l from-transparent to-white dark:to-zinc-900"
	/>
	<div
		class="fixed right-0 w-12 h-full bg-gradient-to-r from-transparent to-white dark:to-zinc-900"
	/>
	<slot />
</main>

// examples/solid-start/src/components/layout.tsx
import type { ParentComponent } from 'solid-js'
import { GrafbaseLogo } from '~/components/icons'

const Layout: ParentComponent = ({ children }) => {
  return (
    <div class="text-black dark:text-white">
      <nav class="flex flex-wrap items-center justify-between p-4 bg-zinc-100 dark:bg-gray-700">
        <div class="flex items-center space-x-6">
          <GrafbaseLogo class="text-black dark:text-white" />
        </div>
      </nav>
      <main class="relative h-[calc(100vh_-_64px)] flex pl-6 pt-6 pr-12 overflow-x-auto dark:bg-zinc-900 transition-colors duration-300">
        <div class="fixed left-0 w-6 h-full bg-gradient-to-l from-transparent to-white dark:to-zinc-900" />
        <div class="fixed right-0 w-12 h-full bg-gradient-to-r from-transparent to-white dark:to-zinc-900" />
        {children}
      </main>
    </div>
  )
}

export default Layout
