// examples/remix/app/components/todo-list.tsx
import { useFetcher } from '@remix-run/react'
import debounce from 'lodash.debounce'
import { useRef } from 'react'
import { Dropdown, DropdownItem } from '~/components/dropdown'
import { DotsVerticalIcon, PencilIcon, TrashIcon } from '~/components/icons'
import TodoItem from '~/components/todo-item'
import TodoItemCreate from '~/components/todo-item-create'
import type { TodoListFragment } from '~/graphql/schema'
import getColor from '~/utils/get-color'

const dropdownItemClass =
  'flex items-center w-full px-2 py-2 text-sm rounded-md group hover:bg-emerald-200 hover:dark:bg-emerald-700'

const TodoList = (props: TodoListFragment) => {
  const { id, title, todos } = props
  const { Form, submission, submit } = useFetcher()
  const inputRef = useRef<HTMLInputElement>(null)

  const isDeleting = submission?.formData.get('_action') === 'todo-list-delete'

  const onTodoListUpdate = (data: { title: string }) => {
    const form = new FormData()
    form.set('_action', 'todo-list-update')
    Object.entries({ id, ...data }).forEach(([key, value]) =>
      form.set(key, `${value}`)
    )
    return submit(form, { method: 'post' })
  }
  const onTitleChange = debounce(
    (title: string) => onTodoListUpdate({ title }),
    500
  )

  return (
    <div hidden={isDeleting} className="space-y-4 flex-1 min-w-[300px]">
      <div
        className="flex justify-between border-b-2"
        title={title || ''}
        style={{ borderColor: getColor(id) }}
      >
        <h2 className="text-xl font-bold truncate">
          <input
            ref={inputRef}
            required
            type="text"
            name="title"
            defaultValue={title}
            onChange={(e) => onTitleChange(e.target.value)}
            className="bg-transparent focus:outline-0 focus:text-blue-600 focus:dark:text-blue-400"
          />
        </h2>
        <div className="relative z-20">
          <Dropdown
            trigger={
              <DotsVerticalIcon className="w-5 h-5 text-gray-400 transition hover:text-red-400" />
            }
          >
            <DropdownItem>
              <button
                onClick={() => setTimeout(() => inputRef.current?.focus(), 100)}
                className={dropdownItemClass}
              >
                <PencilIcon className="w-5 h-5 mr-3" aria-hidden="true" />
                Rename
              </button>
            </DropdownItem>
            <DropdownItem>
              <Form method="post">
                <input type="hidden" name="id" value={id} hidden />
                <button
                  type="submit"
                  name="_action"
                  value="todo-list-delete"
                  aria-label="Delete todo"
                  disabled={isDeleting}
                  className={dropdownItemClass}
                >
                  <TrashIcon className="w-5 h-5 mr-3" aria-hidden="true" />
                  Delete
                </button>
              </Form>
            </DropdownItem>
          </Dropdown>
        </div>
      </div>
      <div className="space-y-4">
        {todos?.edges?.map(
          (edge) =>
            !!edge?.node && <TodoItem key={edge?.node.id} {...edge?.node} />
        )}
      </div>
      <TodoItemCreate todoListId={id} />
    </div>
  )
}

export default TodoList

// examples/solid-start/src/components/todo-list.tsx
import { For } from 'solid-js'
import { createServerAction$, redirect } from 'solid-start/server'
import { Dropdown, DropdownItem } from '~/components/dropdown'
import { DotsVerticalIcon, PencilIcon, TrashIcon } from '~/components/icons'
import TodoItem from '~/components/todo-item'
import TodoItemCreate from '~/components/todo-item-create'
import { Mutation, TodoListDeleteDocument, TodoListFragment, TodoListUpdateDocument } from '~/graphql/schema'
import getColor from '~/utils/get-color'
import { grafbase } from '~/utils/grafbase'

const TodoList = (props: TodoListFragment) => {
  const [deletingTodoList, deleteTodoList] = createServerAction$(async (form: FormData) => {
    const vars = Object.fromEntries(form)
    await grafbase.request<Mutation>(TodoListDeleteDocument, vars)
    return redirect('/')
  })

  const [updatingTodoList, updateTodoList] = createServerAction$(async (form: FormData) => {
    const vars = Object.fromEntries(form)
    await grafbase.request<Mutation>(TodoListUpdateDocument, vars)
    return redirect('/')
  })

  const todos = () => props.todos.edges
  const title = () => (updatingTodoList.pending ? (updatingTodoList.input.get('title') as string) : props.title)
  let inputRef: HTMLInputElement

  return (
    <div class='space-y-4 flex-1 min-w-[300px]'>
      <div class='flex justify-between border-b-2' title={title() || ''} style={{ 'border-color': getColor(props.id) }}>
        <updateTodoList.Form>
          <input type='hidden' name='id' value={props.id} hidden />
          <h2 class='text-xl font-bold truncate'>
            <input
              ref={inputRef}
              required
              type='text'
              name='title'
              value={title()}
              onChange={(e) => {
                if (title() !== e.currentTarget.value) {
                  e.currentTarget.form.requestSubmit()
                }
              }}
              class='bg-transparent focus:outline-0 focus:text-blue-600 focus:dark:text-blue-400'
            />
          </h2>
        </updateTodoList.Form>
        <div class='relative z-20'>
          <Dropdown trigger={<DotsVerticalIcon class='w-5 h-5 text-gray-400 transition hover:text-red-400' />}>
            <DropdownItem>
              <div class='group px-2 py-2 rounded-md hover:bg-emerald-200 hover:dark:bg-emerald-700'>
                <button onClick={() => setTimeout(() => inputRef.focus())} class='flex items-center w-full text-sm'>
                  <PencilIcon class='w-5 h-5 mr-3' aria-hidden='true' />
                  Rename
                </button>
              </div>
            </DropdownItem>
            <DropdownItem>
              <deleteTodoList.Form class='group px-2 py-2 rounded-md hover:bg-emerald-200 hover:dark:bg-emerald-700'>
                <input type='hidden' name='id' value={props.id} hidden />
                <button
                  type='submit'
                  aria-label='Delete todo list'
                  disabled={deletingTodoList.pending}
                  class='flex items-center w-full text-sm'
                >
                  <TrashIcon class='w-5 h-5 mr-3' aria-hidden='true' />
                  Delete
                </button>
              </deleteTodoList.Form>
            </DropdownItem>
          </Dropdown>
        </div>
      </div>
      <div class='space-y-4'>
        <For each={todos()}>{(todo) => !!todo?.node && <TodoItem {...todo.node} />}</For>
      </div>
      <TodoItemCreate todoListId={props.id} />
    </div>
  )
}

export default TodoList
